### ISSUE TITLE
Re-uploading the same test apk breaks the gradle run

### ISSUE THREAD

**Issue by jedi4ever** [browserstack/browserstack-gradle-plugin#15]
It took me a while to figure out ; sometimes you just want to re-run some tests (using the same app & test apk).
When you do this you see a) both getting apks staring to be uploaded b) receive and app url for the first one
but receive also an app_url for the second(test apk) instead of a test_url . 

This results in a vague error {"app_url":"bs://...."}
com.browserstack.json.JSONException: JSONObject["test_url"] not found.
        at com.browserstack.json.JSONObject.get(JSONObject.java:285)
        at com.browserstack.gradle.EspressoTask.uploadTestSuite(EspressoTask.java:165)
        at com.browserstack.gradle.EspressoTask.uploadAndExecuteTest(EspressoTask.java:207)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

When you rebuild it with some change the textcode I assume the checksum has changed and it can be re-uploaded to browserstack.

**Comment by agundawar** [comment]
Thanks for pointing out, We have fixed the issue from our end, Could you please try to run the uploads using the gradle build again?

**Comment by agundawar** [comment]
Closing the issue.
